Gitlab-CI: attempt fix of arch build by manually running triggers
Running the Arch build on certain Runners (especially the Public
CIP-Runners) results in the following errors:

> (5/7) Updating TeXLive filename database...
> error: command failed to execute correctly
> could not change the root directory (Operation not permitted)
> error: command failed to execute correctly
> (6/7) Updating TeXLive format files...
> could not change the root directory (Operation not permitted)
> error: command failed to execute correctly
> (7/7) Updating TeXLive font maps...
> could not change the root directory (Operation not permitted)
> error: command failed to execute correctly

This leads to a failed build, as certain parts of the Texmf-Tree are
then missing, therefore we rebuild the tree explicitly by rerunning the
hooks.